- name: install packages required to install docker
  action: apt pkg={{item}} state=installed
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - python-software-properties

- name: add docker gpg key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
    state: present

- name: update apt
  apt:
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce
    state: latest
    install_recommends: no
